<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sofia Ingersoll">

<title>Spatially Distorted Signaling Wind Infrastructre</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="SDS_Wind_Infrastructure_files/libs/clipboard/clipboard.min.js"></script>
<script src="SDS_Wind_Infrastructure_files/libs/quarto-html/quarto.js"></script>
<script src="SDS_Wind_Infrastructure_files/libs/quarto-html/popper.min.js"></script>
<script src="SDS_Wind_Infrastructure_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="SDS_Wind_Infrastructure_files/libs/quarto-html/anchor.min.js"></script>
<link href="SDS_Wind_Infrastructure_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="SDS_Wind_Infrastructure_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="SDS_Wind_Infrastructure_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="SDS_Wind_Infrastructure_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="SDS_Wind_Infrastructure_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Spatially Distorted Signaling Wind Infrastructre</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sofia Ingersoll </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>In this documentation, the data utilized is the <a href="https://dataverse.harvard.edu/file.xhtml?fileId=7339850&amp;version=1.0">US Wind Data</a>, this data is associated with the “Replication Data for: Prevalence and predictors of wind energy opposition in North America”,[<a href="https://doi.org/10.7910/DVN/LE2V0R" class="uri">doi</a>] Harvard Dataverse, V1, 2023. The collaborators on that project include: Stokes, Leah; Franzblau, Emma; Lovering, Jessica R.; Miljanich, Chris.</p>
<p>Analysis of these areas will provide insight into local resistance and spatially distorted signalling in relation to wind power infrastructure and climate policy.</p>
<p>~ include more about what the data is about and the outcomes of making visualization ~</p>
<p>Main Takeaways:</p>
<ul>
<li><p>Linear Regression Models are not always the answer</p></li>
<li><p>Dude, That’s Logit!</p></li>
<li><p>What in the Log Odds?</p></li>
<li><p>Binary Predictions for Binary Variables</p></li>
</ul>
<section id="loading-libraries" class="level3">
<h3 class="anchored" data-anchor-id="loading-libraries">Loading Libraries</h3>
<p>The following libraries were selected based on their functionality and ability to optimize our data for mapping.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading Libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)        <span class="co"># essential r package </span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)               <span class="co"># package simplifies spatial dataframes</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cowplot)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spData)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(raster)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggspatial)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(prettymapr)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggmap)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stars)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(devtools)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(maptiles)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smoothr)          <span class="co"># aesthetic and visual aid for buffers created</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="read-in-the-data" class="level3">
<h3 class="anchored" data-anchor-id="read-in-the-data">Read in the Data</h3>
<p>To simplify the following step, it is important to organize your folders in a way that makes sense for your workflow. In many cases, the data sets we work with are typically too large to be uploaded to GitHub. As a result, a common practice is storing your data in a folder, directly outside of your repository in a folder labeled “data”.</p>
<p>The code chunk below for <code>read.csv</code> demonstrates how to exit your current location using <code>..</code> and enter the desired folder location using <code>/</code>. It is important that your file path does not contain any spaces and is directly reflective of the file path for the data you wish to read in.</p>
<section id="u.s.-wind-data" class="level4">
<h4 class="anchored" data-anchor-id="u.s.-wind-data">U.S. Wind Data</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># reading in &amp; storing data</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>wind_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../data/wind_data/wind_data_usa.csv"</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="confirm-the-data-loaded-properly" class="level5">
<h5 class="anchored" data-anchor-id="confirm-the-data-loaded-properly">Confirm the Data Loaded Properly</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(wind_data)                  <span class="co"># displays the first 6 rows of the data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X state                    plant_name cen_tract_id region_meta year    status
1 1    OH                    ada school  39065000400     Midwest 2011 Operating
2 2    IL  arends brothers wind turbine  17029000600     Midwest 2009 Operating
3 3    AK                         avtec   2122001300        West 2010 Operating
4 4    OH          bellevue high school  39143962200     Midwest 2010 Operating
5 5    IL                     big windy  17031770800     Midwest 2009 Operating
6 6    WY blm field office wind turbine  56007967800        West 2010 Operating
  community_ownership source median_age protesters_mean letters_use courts_use
1                   1   awea       22.5              NA           0          0
2                   1   awea       44.2              NA          NA         NA
3                   1   awea       39.4              NA          NA         NA
4                   1   awea       38.9              NA          NA         NA
5                   1   awea       35.3              NA          NA         NA
6                   1   awea       38.1              NA           0          0
  legislation_use is_anti_wind  longitude latitude   gop_per med_inc white_perc
1               0            1  -83.83600 40.77500 0.6081081   28103  0.9326417
2              NA            0  -88.02978 39.53132 0.7653214   49704  0.9778930
3              NA            0 -149.43426 60.12564 0.4095064   57532  0.7256915
4              NA            0  -82.84592 41.28236 0.6320885   48879  0.9519143
5              NA            0  -87.86519 41.95547 0.3862876   48900  0.6761018
6               0            0 -107.24175 41.79752 0.6207455   64009  0.7235321
  his_lat_perc  black_perc     pop_den total_mw n_turbs turb_ht
1  0.015035333 0.017591340  553.486602     0.40       1 131.234
2  0.004093886 0.006823144   25.991262     0.10       1  95.100
3  0.028290025 0.018440905    2.540609     0.10       1  95.100
4  0.027575205 0.003874202 1536.689356     0.10       1  95.100
5  0.229487639 0.016839842 3683.457543     0.11       1  78.700
6  0.238095238 0.006703652  400.979020     0.10       1  95.100</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="wrangling-subsetting" class="level2">
<h2 class="anchored" data-anchor-id="wrangling-subsetting">Wrangling &amp; Subsetting</h2>
<section id="converting-latlong-into-raster-data-i.e.-sticky-geometries" class="level3">
<h3 class="anchored" data-anchor-id="converting-latlong-into-raster-data-i.e.-sticky-geometries"><strong>Converting lat/long into Raster Data (i.e.&nbsp;sticky geometries)</strong></h3>
<p>Below we will use the package <code>sf</code> to convert the lat/long data into a raster geometry column. In this single line, we will also be assigning the CRS EPSG:4326 to the sf data frame. Coordinate Reference Systems, CRS, are required in order for the data to be projected onto a map. The CRS was selected because it provides a relatively proportionate display of the United States. We are open to suggestions regarding our CRS if a different project better fits our data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>wind_sf <span class="ot">&lt;-</span> wind_data <span class="sc">%&gt;%</span>             <span class="co"># calls desired dataset</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>), <span class="at">crs =</span> <span class="dv">4326</span>) </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                                     <span class="co"># creates geometry column with desired crs </span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(<span class="fu">crs</span>(wind_sf))                  <span class="co"># output should reveal WGS84, EPSG:4326</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> chr "GEOGCRS[\"WGS 84\",\n    ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n        MEMBER[\"World Geodetic Sys"| __truncated__</code></pre>
</div>
</div>
<section id="check-point" class="level4">
<h4 class="anchored" data-anchor-id="check-point">Check-point</h4>
<p>Let’s stop and see if our outputs are what we expect.</p>
<p>Were the lat/long columns correctly converted into a geometry column?</p>
<p><code>setdiff()</code> is a way to quickly determine the differences between two data sets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setdiff</span>(<span class="fu">colnames</span>(wind_data), <span class="fu">colnames</span>(wind_sf))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "longitude" "latitude" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setdiff</span>(<span class="fu">colnames</span>(wind_sf), <span class="fu">colnames</span>(wind_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "geometry"</code></pre>
</div>
</div>
</section>
</section>
<section id="initial-visualization-of-the-data" class="level3">
<h3 class="anchored" data-anchor-id="initial-visualization-of-the-data">Initial Visualization of the Data</h3>
<p>Using the base R function <code>plot()</code>, we can see that the geometries stored by this data set correlate to the locations of wind infrastructure plants throughout the United States. In order to visualize these locations with respect to state and county jurisdictions, we’ll need to utilize another data set to create a base layer for our map.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First visual of the U.S. wind data provided by the geometry points</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>wind_plants <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(wind_sf) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotation_map_tile</span>(<span class="at">type =</span> <span class="st">"osm"</span>) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">col =</span> <span class="st">'darkgreen'</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">alpha =</span> <span class="fl">0.5</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">size =</span> <span class="dv">3</span>) </span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>wind_plants</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="SDS_Wind_Infrastructure_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="linear-regression-models" class="level1">
<h1>Linear Regression Models</h1>
<section id="variables-of-interest" class="level3">
<h3 class="anchored" data-anchor-id="variables-of-interest">Variables of Interest:</h3>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>status</td>
<td>describes the operating status of wind infrastructure, binary variable. 1 is operating, 0 is not_operating.</td>
</tr>
<tr class="even">
<td>pop_den</td>
<td>population density of census tract ids within 3km buffer of wind infrastructure.</td>
</tr>
<tr class="odd">
<td>med_inc</td>
<td>defines the median income of census tract ids within 3km buffer zone of wind infrastructure.</td>
</tr>
<tr class="even">
<td>median_age</td>
<td>describes the median age of census tract ids within 3 km radius of wind infrastructure.</td>
</tr>
</tbody>
</table>
<p>An attribute from each column will be used to run several multivariate linear regression models. This is to assess the effects of socioeconmic/regional influences on wind infrastructure and the estimated likelihood of participating legislative action when living within a 3km proximity of a wind plant.</p>
</section>
<section id="determining-variable-assignments-for-ols" class="level2">
<h2 class="anchored" data-anchor-id="determining-variable-assignments-for-ols">Determining Variable Assignments for OLS</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(wind_sf<span class="sc">$</span>status)     <span class="co"># displays unique values in this</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Operating"                    "Cancelled"                   
[3] "Out of service (temporarily)" "Standby"                     
[5] "Decommissioned"               "Operating | Decommissioned"  
[7] NA                            </code></pre>
</div>
</div>
<section id="need-to-rename-status-output-variables" class="level3">
<h3 class="anchored" data-anchor-id="need-to-rename-status-output-variables">Need to rename status output variables</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creating two categories: operating &amp; not_operating</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># We are removing 'Operating | Decommissioned' because it skews the data</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>unwanted_status <span class="ot">&lt;-</span> <span class="st">"Operating | Decommissioned"</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>replacement_status <span class="ot">&lt;-</span> <span class="st">"Uncertain Status"</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>wind_sf<span class="sc">$</span>status[wind_sf<span class="sc">$</span>status<span class="sc">==</span> unwanted_status]<span class="ot">&lt;-</span><span class="st">"Uncertain Status"</span>  </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># were we successful ?</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(wind_sf<span class="sc">$</span>status)     <span class="co"># displays unique values in this</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Operating"                    "Cancelled"                   
[3] "Out of service (temporarily)" "Standby"                     
[5] "Decommissioned"               "Uncertain Status"            
[7] NA                            </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># cleaning out NAs for OLS</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>wind_sf <span class="ot">&lt;-</span> wind_sf <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(status) <span class="sc">==</span> <span class="st">'FALSE'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(is_anti_wind) <span class="sc">==</span> <span class="st">'FALSE'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(pop_den) <span class="sc">==</span> <span class="st">'FALSE'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(med_inc) <span class="sc">==</span> <span class="st">'FALSE'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(median_age) <span class="sc">==</span> <span class="st">'FALSE'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(n_turbs) <span class="sc">==</span> <span class="st">'FALSE'</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="co"># were we successful ?</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(wind_sf<span class="sc">$</span>status)     <span class="co"># displays unique values in this</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Operating"                    "Cancelled"                   
[3] "Out of service (temporarily)" "Standby"                     
[5] "Decommissioned"               "Uncertain Status"            </code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># if_else preserves the data type but replaces unwanted values</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>wind_us <span class="ot">&lt;-</span> wind_sf <span class="sc">%&gt;%</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">status =</span> <span class="fu">if_else</span>(</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    status <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">'Cancelled'</span>, <span class="st">'Out of service (temporarily)'</span>, <span class="st">'Standby'</span>, <span class="st">'Decommissioned'</span>, <span class="st">'Uncertain Status'</span>), <span class="st">'not_operating'</span>,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'operating'</span>) </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co"># are our only outputs "operating" and "not_operating"?</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">unique</span>(wind_us<span class="sc">$</span>status))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "operating"     "not_operating"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># status as factor and reassigned values</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>wind_us <span class="ot">&lt;-</span> wind_us <span class="sc">%&gt;%</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">status =</span> <span class="fu">case_when</span>(status <span class="sc">==</span> <span class="st">"operating"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>            status <span class="sc">==</span> <span class="st">"not_operating"</span> <span class="sc">~</span> <span class="dv">0</span>))</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co"># are our only outputs 0 or 1?</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">unique</span>(wind_us<span class="sc">$</span>status))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 0</code></pre>
</div>
</div>
<p>Binary variable will be <code>status</code> column: <code>opertating</code> is 1, and <code>not_operating</code> will be 0.</p>
</section>
</section>
<section id="dude-thats-logit" class="level2">
<h2 class="anchored" data-anchor-id="dude-thats-logit">Dude, that’s Logit!</h2>
<section id="initial-visualization-of-categorical-response-variable" class="level3">
<h3 class="anchored" data-anchor-id="initial-visualization-of-categorical-response-variable">Initial Visualization of Categorical Response Variable</h3>
<p>Our initial visualization demonstrates a correlation between smaller population density and wind infrastructure plants operating. This is likely associated with weight placed on voters in regions with smaller demographics. Local mobilization of minority opinion holders in these regions have a greater availability to push back against policymakers. However, this visual does not encapsulate all of the necessary information required to determine this with full certainty.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># visualization of relationship</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>jitter_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> wind_us, </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">aes</span>(<span class="at">x =</span> pop_den,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">y =</span> status)) <span class="sc">+</span> </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">col =</span> <span class="st">'plum'</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill =</span> <span class="st">"purple"</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">width =</span> <span class="dv">0</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">height =</span> <span class="fl">0.05</span>,</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">alpha =</span> <span class="fl">0.45</span>,</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Population Density &amp; Wind Infrastructure Activation Status"</span>,</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Population Density"</span>,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Wind Infrastructure Operating Status"</span>)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>jitter_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="SDS_Wind_Infrastructure_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># useful information</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wind_us<span class="sc">$</span>pop_den)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
    0.143     4.309    12.493   181.484    40.394 13940.515 </code></pre>
</div>
</div>
</section>
</section>
<section id="logistic-regressions-with-binomial-family" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regressions-with-binomial-family">Logistic Regressions with Binomial Family:</h2>
<section id="binary-dependent-variable" class="level3">
<h3 class="anchored" data-anchor-id="binary-dependent-variable">Binary Dependent Variable</h3>
<p><span class="math display">\[ \text{status}\ = \beta_0 + \beta_1 \text{pop_den}\_i + \varepsilon_i \]</span></p>
<ul>
<li><p>Our summary table describes a null deviance <code>362.60</code>.(<code>1178 df</code>) and residual deviance <code>362.22</code> (<code>1177 df</code>).</p></li>
<li><p>A p-value of <code>0.593</code> for <span class="math inline">\(\beta_1\)</span>, is greater than the significant value of 0.05, therefore, the model hypothesis that operation status is influenced by population density holds.</p></li>
<li><p>However, I am still not convinced there isn’t a correlation shared with another factor, so let’s explore how our numbers change as we incorporate more variables into our equation later on.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inital regression 1 betas for null</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># function</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>status <span class="ot">&lt;-</span> <span class="fu">glm</span>(status <span class="sc">~</span> pop_den,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                       wind_us,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">family =</span> <span class="st">'binomial'</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># summary to access coefficients</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>status1 <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">glm</span>(status <span class="sc">~</span> pop_den,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>                       wind_us,</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>                       <span class="at">family =</span> <span class="st">'binomial'</span>))</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="co"># show me a summary table </span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>status1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = status ~ pop_den, family = "binomial", data = wind_us)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) 3.2721930  0.1623175  20.159   &lt;2e-16 ***
pop_den     0.0001793  0.0003356   0.534    0.593    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 362.60  on 1178  degrees of freedom
Residual deviance: 362.22  on 1177  degrees of freedom
AIC: 366.22

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
</section>
</section>
<section id="what-in-the-log-odds" class="level2">
<h2 class="anchored" data-anchor-id="what-in-the-log-odds">What in the Log Odds?</h2>
<p>So far, we haven’t been able to gather very much useful information to describe our model predictions. If this were a typical OLS, our model would be telling us:</p>
<ul>
<li>When wind turbines are operational, and all other variables are held constant at 0, the <span class="math inline">\(\beta_0\)</span> represents the estimated likelihood that <code>status</code> of a wind infrastructure plant is <code>operating</code> is ~ <code>3.27</code>.</li>
</ul>
<!-- -->
<ul>
<li><span class="math inline">\(\beta_1\)</span> tells us there is an estimated increase of <code>1.79e-04</code> in probability that status would be <code>operating</code> for the average unit increase in <code>pop_den</code>.</li>
</ul>
<p>Since we’re working with a binomial family, the p-values produced in the <code>glm()</code> need to be further extrapolated before they may be used to interpret our model.</p>
<p>Our model that we just fit tells us that:</p>
<section id="logitplog-p-1pβ0β1xε" class="level4">
<h4 class="anchored" data-anchor-id="logitplog-p-1pβ0β1xε"><span class="math display">\[logit(p)=log( p / 1−p)=β0+β1x+ε\]</span></h4>
<p>so then, to solve for p:</p>
<p><span class="math display">\[
p̂=e^(β0+β1x1+eβ0+β1x)
\]</span></p>
<p>Alternatively, we’re going to solve for p using&nbsp;<span class="math inline">\(R^2\)</span> because that looks gross. The&nbsp;<code>uniroot</code>&nbsp;function searches over the provided interval to find the zero value of the function provided. We pass the expression that should equal zero, and it finds us the p that ensures it equals zero.</p>
</section>
<section id="finding-p" class="level3">
<h3 class="anchored" data-anchor-id="finding-p">Finding p</h3>
<p>Utilizing the funky relationship described above, we can solve for a range of p values using <span class="math inline">\(R^2\)</span>. We’re curious about the probability of <code>operating</code> wind plants for Population Density at <code>20,000</code>, <code>6,000</code>, and <code>600.</code> H</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creating a function to to describe the logistic regression model</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 100,000 </span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>fun <span class="ot">&lt;-</span> <span class="cf">function</span>(p) {</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">1</span> <span class="sc">-</span> p)<span class="sc">*</span><span class="fu">exp</span>(status1<span class="sc">$</span>coefficients[<span class="dv">1</span>,<span class="st">'Estimate'</span>] <span class="sc">+</span> (status1<span class="sc">$</span>coefficients[<span class="dv">2</span>,<span class="st">'Estimate'</span>]<span class="sc">*</span><span class="dv">20000</span>)) <span class="sc">-</span> p</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="fu">uniroot</span>(fun, <span class="at">interval =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))<span class="sc">$</span>root</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9989509</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 26000</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>fun <span class="ot">&lt;-</span> <span class="cf">function</span>(p) {</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">1</span> <span class="sc">-</span> p)<span class="sc">*</span><span class="fu">exp</span>(status1<span class="sc">$</span>coefficients[<span class="dv">1</span>,<span class="st">'Estimate'</span>] <span class="sc">+</span> (status1<span class="sc">$</span>coefficients[<span class="dv">2</span>,<span class="st">'Estimate'</span>]<span class="sc">*</span><span class="dv">6000</span>)) <span class="sc">-</span> p</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="fu">uniroot</span>(fun, <span class="at">interval =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))<span class="sc">$</span>root</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9872347</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 6000</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>fun <span class="ot">&lt;-</span> <span class="cf">function</span>(p) {</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">1</span> <span class="sc">-</span> p)<span class="sc">*</span><span class="fu">exp</span>(status1<span class="sc">$</span>coefficients[<span class="dv">1</span>,<span class="st">'Estimate'</span>] <span class="sc">+</span> (status1<span class="sc">$</span>coefficients[<span class="dv">2</span>,<span class="st">'Estimate'</span>]<span class="sc">*</span><span class="dv">600</span>)) <span class="sc">-</span> p</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="fu">uniroot</span>(fun, <span class="at">interval =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))<span class="sc">$</span>root</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.967067</code></pre>
</div>
</div>
</section>
<section id="logistic-regression-visualization" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression-visualization">Logistic Regression Visualization</h3>
<p>This visual is very interesting and definitely explains why the <span class="math inline">\(R^2\)</span> value is only giving values in the 0.9 range. Since our data contains a significant number of <code>operating</code> wind plants for a wide range of population densities, the regression model is producing a fit according to the <code>operating</code> status. The values in the <code>not_opertating</code> status appear to be considered similar to that of an outlier.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="SDS_Wind_Infrastructure_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="interpreting-coefficients-using-odds-ratio" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-coefficients-using-odds-ratio">Interpreting Coefficients Using Odds Ratio</h3>
<p>To better interpret this relationship, we are going to change the scale of the variable on the y-axis. Now, we will be considering the odds, rather than the probability. While these two concepts are often conflated, they are not the same[<a href="https://tcarleton.github.io/EDS-222-stats/labs/06-week-six/week-6-lab-answers.html">2</a>]. They are however, related by the simple formula below.</p>
<p>The&nbsp;<strong>odds</strong>&nbsp;of a binary event are the ratio of how often it happens, to how often it doesn’t happen.</p>
<p><span class="math inline">\(odds(p̂)=p̂1−p̂=exp(β̂0+β̂1⋅x)\)</span></p>
<p>We’re going create an&nbsp;<code>status_popden_odds</code>&nbsp;variable for predicted odds.</p>
<p>That is, the ratio of the odds&nbsp;<em>after</em>&nbsp;a one unit increase in&nbsp;x&nbsp;to the odds <em>before</em> that one unit change is equal to&nbsp;eβ1.&nbsp;<strong>Notice this doesn’t depend on</strong> x&nbsp;anymore! Therefore, it’s a useful interpretation of coefficients.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>status_popden_predicted_odds <span class="ot">&lt;-</span>  status <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(<span class="at">type.predict =</span> <span class="st">"response"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">y_hat =</span> .fitted) <span class="sc">%&gt;%</span> </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">odds_hat =</span> y_hat <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> y_hat))</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>status_popden_predicted_odds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,179 × 10
   status pop_den .fitted .resid     .hat .sigma   .cooksd .std.resid y_hat
    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;
 1      1  553.     0.967  0.260 0.00147   0.555 0.0000253      0.260 0.967
 2      1   26.0    0.964  0.272 0.000901  0.555 0.0000170      0.272 0.964
 3      1    2.54   0.963  0.273 0.000925  0.555 0.0000176      0.273 0.963
 4      1 1537.     0.972  0.238 0.00681   0.555 0.0000994      0.239 0.972
 5      1 3683.     0.981  0.197 0.0274    0.555 0.000284       0.200 0.981
 6      1  401.     0.966  0.263 0.00110   0.555 0.0000195      0.264 0.966
 7      1   46.9    0.964  0.272 0.000884  0.555 0.0000167      0.272 0.964
 8      1  113.     0.964  0.270 0.000853  0.555 0.0000159      0.270 0.964
 9      1   40.5    0.964  0.272 0.000889  0.555 0.0000168      0.272 0.964
10      1 2529.     0.976  0.218 0.0156    0.555 0.000194       0.220 0.976
# ℹ 1,169 more rows
# ℹ 1 more variable: odds_hat &lt;dbl&gt;</code></pre>
</div>
</div>
<p>This is an “odds ratio”, meaning we care about how this number differs from 1. If it’s greater than 1, then the odds increase when&nbsp;x&nbsp;increases. Conversely, if it’s less than 1, then the odds decrease.</p>
<ul>
<li>By how much does our model predict that the odds of <code>operating status</code> will change with each additional unit increase in population density?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(status1<span class="sc">$</span>coefficients[<span class="dv">2</span>,<span class="st">'Estimate'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.000179</code></pre>
</div>
</div>
<p><strong>Answer:</strong>&nbsp;Our model estimates that one unit increase in population density is associated with a change in the odds ratio of <span class="math inline">\(e^(0.0001793) =1.000179\)</span>, or a 1.79e-04% increase in the odds of wind plant having an <code>operating</code> status.</p>
</section>
<section id="logistic-model-with-2-continous-variables" class="level3">
<h3 class="anchored" data-anchor-id="logistic-model-with-2-continous-variables">Logistic Model with 2 Continous Variables</h3>
<p><span class="math display">\[ \text{status}\ = \beta_0 + \beta_1 \text{pop_den}\_i + \beta_2 \text{med_inc} + \varepsilon_i \]</span></p>
<ul>
<li><p>Our summary table describes a null deviance 362.60.(1178 df) and residual deviance 359.84 (1176 df).</p></li>
<li><p>Additionally, it provides a p-value of 0.511 for <span class="math inline">\(\beta_1\)</span>, indicating that the hypothesis here is accepted because it is greater than the significant value of 0.05.</p></li>
<li><p>The p-value of <span class="math inline">\(\beta_2\)</span>, 0.957s is acceptable because it is above range of the significant value.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>status_2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(status <span class="sc">~</span> pop_den <span class="sc">+</span> med_inc,</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>               wind_us,</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">family =</span> <span class="st">'binomial'</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Initial regression 2 betas for null</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>status2 <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">glm</span>(status <span class="sc">~</span> pop_den <span class="sc">+</span> med_inc,</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>               wind_us,</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">family =</span> <span class="st">'binomial'</span>))</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>status2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = status ~ pop_den + med_inc, family = "binomial", 
    data = wind_us)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  4.028e+00  4.950e-01   8.138 4.03e-16 ***
pop_den      2.477e-04  3.776e-04   0.656   0.5118    
med_inc     -1.497e-05  8.988e-06  -1.666   0.0957 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 362.60  on 1178  degrees of freedom
Residual deviance: 359.84  on 1176  degrees of freedom
AIC: 365.84

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<section id="interpreting-coefficients-using-odds-ratio-1" class="level4">
<h4 class="anchored" data-anchor-id="interpreting-coefficients-using-odds-ratio-1">Interpreting Coefficients using Odds Ratio</h4>
<p>In a typical OLS model, we would intuitively want to assume the following from our model:</p>
<ul>
<li><p>When wind turbines are operational, and all other variables are held constant at 0, the <span class="math inline">\(\beta_0\)</span> represents the estimated likelihood that status of a wind infrastructure plant is operating is ~ 4.03.</p></li>
<li><p><span class="math inline">\(\beta_1\)</span> tells us there is an estimated decrease of 2.47e-4 in probability that status would be operating for the average unit increase in is_anti_wind opinion holders.</p></li>
<li><p>For every average unit increase in pop_den, <span class="math inline">\(\beta_2\)</span> predicts 1.50e-05 will increase the operating status, indicating pop_den is an extremely marginal influence, that may potentially be interacting with is_anti_wind outlook.</p></li>
</ul>
<p>However, it’s important to remember that we still need to exponentiate our estimated values in order to obtain our p-values. We’re here to break the status quo and train our brains to interpret logistic regressions.</p>
</section>
<section id="logitplog-p-1pβ0β1xε-1" class="level4">
<h4 class="anchored" data-anchor-id="logitplog-p-1pβ0β1xε-1"><span class="math display">\[logit(p)=log( p / 1−p)=β0+β1x+ε\]</span></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># beta1 estimation exponentiated</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(status2<span class="sc">$</span>coefficients[<span class="dv">2</span>,<span class="st">'Estimate'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.000248</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># beta2 estimation exponentiated</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">exp</span>(status2<span class="sc">$</span>coefficients[<span class="dv">3</span>,<span class="st">'Estimate'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.497159e-05</code></pre>
</div>
</div>
<p>By including the median income variable in our model and exponentiating the coefficients, we see a huge effect. Areas with an increase in population density observed an increase in their odds of having active wind infrastructure by a factor of 2.48e-04% when controlling the median income. However, the odds of operating status decrease by 1.5e-05 for each average unit increase in median income.</p>
</section>
</section>
</section>
<section id="probabilistic-predictions" class="level2">
<h2 class="anchored" data-anchor-id="probabilistic-predictions">Probabilistic Predictions</h2>
<p>We are going to making some probability predictions using out-of-sample predictions using the <code>type.predict</code> argument set as “response”, to retrieve fitted values on the familiar probability scale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># probability scale</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>probability_predictions <span class="ot">&lt;-</span> <span class="fu">augment</span>(status_2, <span class="at">type.predict =</span> <span class="st">"response"</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>probability_predictions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,179 × 9
   status pop_den med_inc .fitted .resid     .hat .sigma   .cooksd .std.resid
    &lt;dbl&gt;   &lt;dbl&gt;   &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
 1      1  553.     28103   0.977  0.216 0.00251   0.553 0.0000199      0.216
 2      1   26.0    49704   0.964  0.270 0.000917  0.553 0.0000114      0.271
 3      1    2.54   57532   0.960  0.287 0.00113   0.553 0.0000159      0.287
 4      1 1537.     48879   0.975  0.224 0.00764   0.553 0.0000655      0.224
 5      1 3683.     48900   0.985  0.172 0.0268    0.553 0.000140       0.174
 6      1  401.     64009   0.960  0.287 0.00166   0.553 0.0000234      0.287
 7      1   46.9    82210   0.943  0.342 0.00525   0.553 0.000107       0.343
 8      1  113.     52788   0.963  0.274 0.000877  0.553 0.0000112      0.274
 9      1   40.5    49875   0.964  0.270 0.000903  0.553 0.0000112      0.270
10      1 2529.     58076   0.978  0.212 0.0183    0.553 0.000144       0.214
# ℹ 1,169 more rows</code></pre>
</div>
</div>
<p>For example, our model predicts the odds that an area with a population density of 124 and a median income of 46,094 and would have an operating wind plant is ~97%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>exploring_model <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">pop_den =</span> <span class="dv">124</span>, <span class="at">med_inc =</span> <span class="dv">46094</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(status_2, <span class="at">newdata =</span> exploring_model, <span class="at">type.predict =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  pop_den med_inc .fitted
    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1     124   46094   0.967</code></pre>
</div>
</div>
</section>
<section id="binary-predictions" class="level2">
<h2 class="anchored" data-anchor-id="binary-predictions">Binary Predictions</h2>
<section id="model-containing-binary-independent-variable" class="level4">
<h4 class="anchored" data-anchor-id="model-containing-binary-independent-variable">Model Containing Binary Independent Variable</h4>
<p><span class="math display">\[ \text{status}\ = \beta_0 + \beta_1 \text{pop_den}\_i + + \beta_2 \text{is_anti_wind} + \varepsilon_i \]</span></p>
<ul>
<li><p>Our summary table describes a null deviance 362.60.(1178 df) and residual deviance 289.8 (1175 df).</p></li>
<li><p>Additionally, it provides a p-value of 1.03e-14 for <span class="math inline">\(\beta_1\)</span>, indicating that the hypothesis here is rejected because it is drastically smaller than the significant value of 0.05.</p></li>
<li><p>The p-value of <span class="math inline">\(\beta_2\)</span>, 0.668 is acceptable because it is within range of the significant value.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression with 3 beta</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="co"># function</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>status_3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(status <span class="sc">~</span> pop_den <span class="sc">+</span> is_anti_wind, </span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>                       wind_us,</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">family =</span> <span class="st">'binomial'</span>)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="co"># stored summary</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>status3 <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">glm</span>(status <span class="sc">~</span> pop_den <span class="sc">+</span> is_anti_wind, </span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>                       wind_us,</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>                       <span class="at">family =</span> <span class="st">'binomial'</span>))</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>status3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = status ~ pop_den + is_anti_wind, family = "binomial", 
    data = wind_us)

Coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   4.467e+00  3.076e-01  14.524  &lt; 2e-16 ***
pop_den       7.565e-05  3.304e-04   0.229    0.819    
is_anti_wind -2.798e+00  3.612e-01  -7.746 9.47e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 362.60  on 1178  degrees of freedom
Residual deviance: 292.13  on 1176  degrees of freedom
AIC: 298.13

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
</section>
<section id="interpreting-coefficients-using-odds-ratio-2" class="level4">
<h4 class="anchored" data-anchor-id="interpreting-coefficients-using-odds-ratio-2">Interpreting Coefficients using Odds Ratio</h4>
<p>So, after some manipulation, we find that the odds ratio gives us some good information.</p>
<ul>
<li>Areas with an increase in population density observed an increase in their odds of having active wind infrastructure by a factor of 7.6e-05% when controlling the local opinion on wind constant. However, the odds of operating status decrease by ~7% for areas that identify as anti wind infrastructure.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># beta1 estimation exponentiated</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(status3<span class="sc">$</span>coefficients[<span class="dv">2</span>,<span class="st">'Estimate'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.000076</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># beta2 estimation exponentiated</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">exp</span>(status3<span class="sc">$</span>coefficients[<span class="dv">3</span>,<span class="st">'Estimate'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9390681</code></pre>
</div>
</div>
</section>
<section id="table-of-binary-predictions" class="level4">
<h4 class="anchored" data-anchor-id="table-of-binary-predictions">Table of Binary Predictions</h4>
<p>What do these predictions tell us?</p>
<p>Well, they lend us some insight into whether or not we can definitively predict the status outcome of a region depending on their population density and position on wind opposition. They additionally provide the model fit (<span class="math inline">\(R^2\)</span>) value associated with the predicted value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>status_binary <span class="ot">&lt;-</span> <span class="fu">augment</span>(status_3, <span class="at">type.predict =</span> <span class="st">"response"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">operating_hat =</span> <span class="fu">round</span>(.fitted))</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>binary_predictions <span class="ot">&lt;-</span> status_binary <span class="sc">%&gt;%</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(status, pop_den, is_anti_wind, .fitted, operating_hat)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>binary_predictions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,179 × 5
   status pop_den is_anti_wind .fitted operating_hat
    &lt;dbl&gt;   &lt;dbl&gt;        &lt;int&gt;   &lt;dbl&gt;         &lt;dbl&gt;
 1      1  553.              1   0.847             1
 2      1   26.0             0   0.989             1
 3      1    2.54            0   0.989             1
 4      1 1537.              0   0.990             1
 5      1 3683.              0   0.991             1
 6      1  401.              0   0.989             1
 7      1   46.9             0   0.989             1
 8      1  113.              0   0.989             1
 9      1   40.5             0   0.989             1
10      1 2529.              0   0.991             1
# ℹ 1,169 more rows</code></pre>
</div>
</div>
</section>
<section id="considering-omitted-variable-bias-ovb" class="level4">
<h4 class="anchored" data-anchor-id="considering-omitted-variable-bias-ovb">Considering Omitted Variable Bias (OVB)</h4>
<p>Neglecting additional variables without testing is bad practice. Exogeneity is a very difficult OLS assumption to uphold – alongside a normal distribution of the error mean. A means to determine relationships between variables is running various linear regression models and comparing the <span class="math inline">\(R^2\)</span> value. In this project, we focused our attention on the why OLS was not the analysis method of choice for our relationships of interest. In the instance of logistic regression, a log odds ratio must be taken to interpret each individual variable. There is a strong possibility that the models utilized in this project are not exogenous and require deeper analysis to determine the impact of underlining influences.</p>
</section>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section"></h3>
<p>--------------------------------------------------</p>
<p>if time allows</p>
<section id="textstatus-beta_0-beta_1-textpop_den_i-beta_2-textmedian_age-beta_3-textpop_den-median_age-varepsilon_i-when-wind-turbines-are-operational-and-all-other-variables-are-held-constant-at-0-the-beta_0-represents-the-estimated-likelihood-that-status-of-a-wind-infrastructure-plant-is-operating-is-4.23.beta_1-tells-us-there-is-an-estimated-decrease-of-2.81-in-probability-that-status-would-be-operating-for-the-average-unit-increase-in-is_anti_wind-opinion-holders.for-every-average-unit-increase-in-pop_den-beta_2-predicts-1.65e-04-will-increase-the-operating-status-indicating-pop_den-is-an-extremely-marginal-influence-that-may-potentially-be-interacting-with-is_anti_wind-outlook.beta_3-predicts-1.79e-05-will-decrease-the-operating-status-for-an-average-unit-increase-in-med_inc.beta_4-estimates-an-increase-of-2.73e-02-in-the-operating-status-for-each-average-unit-increase-in-med_age.our-summary-table-describes-a-null-deviance-362.60.1178-df-and-residual-deviance-289.02-1174-df.additionally-it-provides-a-p-value-of-9.17e-15-for-beta_1-indicating-that-the-hypothesis-here-is-rejected-because-it-is-drastically-smaller-than-the-significant-value-of-0.05.the-p-value-of-beta_2-0.553-is-acceptable-because-it-is-within-range-of-the-significant-value.the-p-value-of-beta_3-0.096-is-acceptable-because-it-is-within-range-of-the-significant-value.the-p-value-of-beta_4-0.370-is-acceptable-because-it-is-within-range-of-the-significant-value.r-regression-with-interacting-betastatus5---glmstatus-pop_den-median_age-pop_den-median_age-wind_us-family-binomialsummarystatus5" class="level5">
<h5 class="anchored" data-anchor-id="textstatus-beta_0-beta_1-textpop_den_i-beta_2-textmedian_age-beta_3-textpop_den-median_age-varepsilon_i-when-wind-turbines-are-operational-and-all-other-variables-are-held-constant-at-0-the-beta_0-represents-the-estimated-likelihood-that-status-of-a-wind-infrastructure-plant-is-operating-is-4.23.beta_1-tells-us-there-is-an-estimated-decrease-of-2.81-in-probability-that-status-would-be-operating-for-the-average-unit-increase-in-is_anti_wind-opinion-holders.for-every-average-unit-increase-in-pop_den-beta_2-predicts-1.65e-04-will-increase-the-operating-status-indicating-pop_den-is-an-extremely-marginal-influence-that-may-potentially-be-interacting-with-is_anti_wind-outlook.beta_3-predicts-1.79e-05-will-decrease-the-operating-status-for-an-average-unit-increase-in-med_inc.beta_4-estimates-an-increase-of-2.73e-02-in-the-operating-status-for-each-average-unit-increase-in-med_age.our-summary-table-describes-a-null-deviance-362.60.1178-df-and-residual-deviance-289.02-1174-df.additionally-it-provides-a-p-value-of-9.17e-15-for-beta_1-indicating-that-the-hypothesis-here-is-rejected-because-it-is-drastically-smaller-than-the-significant-value-of-0.05.the-p-value-of-beta_2-0.553-is-acceptable-because-it-is-within-range-of-the-significant-value.the-p-value-of-beta_3-0.096-is-acceptable-because-it-is-within-range-of-the-significant-value.the-p-value-of-beta_4-0.370-is-acceptable-because-it-is-within-range-of-the-significant-value.r-regression-with-interacting-betastatus5---glmstatus-pop_den-median_age-pop_den-median_age-wind_us-family-binomialsummarystatus5"><span class="math display">\[ \text{status}\ = \beta_0 + \beta_1 \text{pop_den}\_i + \beta_2 \text{median_age} + \beta_3 \text{pop_den * median_age} + \varepsilon_i \]</span>When wind turbines are operational, and all other variables are held constant at 0, the <span class="math inline">\(\beta_0\)</span> represents the estimated likelihood that <code>status</code> of a wind infrastructure plant is <code>operating</code> is ~ <code>4.23</code>.<span class="math inline">\(\beta_1\)</span> tells us there is an estimated decrease of <code>2.81</code> in probability that status would be <code>operating</code> for the average unit increase in <code>is_anti_wind</code> opinion holders.For every average unit increase in <code>pop_den</code>, <span class="math inline">\(\beta_2\)</span> predicts <code>1.65e-04</code> will increase the <code>operating status</code>, indicating <code>pop_den</code> is an extremely marginal influence, that may potentially be interacting with <code>is_anti_wind</code> outlook.<span class="math inline">\(\beta_3\)</span> predicts <code>1.79e-05</code> will decrease the <code>operating status</code>, for an average unit increase in <code>med_inc</code>.<span class="math inline">\(\beta_4\)</span> estimates an increase of <code>2.73e-02</code> in the <code>operating status</code>, for each average unit increase in <code>med_age</code>.Our summary table describes a null deviance <code>362.60</code>.(<code>1178 df</code>) and residual deviance <code>289.02</code> (<code>1174 df</code>).Additionally, it provides a p-value of <code>9.17e-15</code> for <span class="math inline">\(\beta_1\)</span>, indicating that the hypothesis here is rejected because it is drastically smaller than the <code>significant value of 0.05</code>.The p-value of <span class="math inline">\(\beta_2\)</span>, <code>0.553</code> is acceptable because it is within range of the significant value.The p-value of <span class="math inline">\(\beta_3\)</span>, <code>0.096</code> is acceptable because it is within range of the significant value.The p-value of <span class="math inline">\(\beta_4\)</span>, ~<code>0.370</code> is acceptable because it is within range of the significant value.<code>{r}# Regression with interacting betastatus5 &lt;- glm(status ~ pop_den + median_age + pop_den * median_age,                        wind_us,                       family = 'binomial')summary(status5)</code></h5>
</section>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>